<a href="https://colab.research.google.com/github/Tienndat2306/TH_DeepLearning/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np

Bài 1. Tensor 0 chiều

In [4]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)
r1 = tf.constant(9, tf.int16)
print(r1)
r1_float = tf.constant(1.12, tf.float32)
print(r1_float)
r1_string = tf.constant('Hello Vu', tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vu', shape=(), dtype=string)


Bài 2. Tensor 1 chiều

In [6]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


Bài 3. Tensor 2 chiều (Ma trận)

In [7]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]
                             ], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


Bài 4. Tensor n chiều

In [8]:
rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],
])
print(rank_3_tensor)

tf.Tensor(
[[[0 1 2 3 4]
  [5 6 7 8 9]]

 [[0 1 2 3 4]
  [5 6 7 8 9]]

 [[0 1 2 3 4]
  [5 6 7 8 9]]], shape=(3, 2, 5), dtype=int32)
